/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const StockItem = IDL.Record({
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addStockItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'getAllStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
  'getStockItem' : IDL.Func([IDL.Text], [StockItem], ['query']),
  'removeStockItem' : IDL.Func([IDL.Text], [], []),
  'updateStockItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const StockItem = IDL.Record({
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addStockItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'getAllStockItems' : IDL.Func([], [IDL.Vec(StockItem)], ['query']),
    'getStockItem' : IDL.Func([IDL.Text], [StockItem], ['query']),
    'removeStockItem' : IDL.Func([IDL.Text], [], []),
    'updateStockItem' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };